language: objective-c
osx_image: xcode9.1

script:
  - set -o pipefail
  - xcodebuild clean test -project HDF5Kit.xcodeproj -scheme "HDF5Kit-OSX"
  - xcodebuild clean test -project HDF5Kit.xcodeproj -scheme "HDF5Kit-iOS" -destination 'platform=iOS Simulator,name=iPhone 7'

after_success:
  - bash <(curl -s https://codecov.io/bash)
